name: 'Google Cloud Storage Bucket Sync (GCP,GCS)'
description: 'Sync a Github repository with a Google Cloud Storage (GCS) bucket'
author: 'Patrick Wyler'

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: Bucket name
    required: true
  subdirectory:
    description: Subdirectory name
    required: false
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: '.git$'

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: gray-dark
